language: node_js

addons:
  ssh_known_hosts:
  - beta.fuelrats.com
  - cheddar.fuelrats.com
  apt:
    update: true


cache: yarn


before_install:
- sudo apt-get install -y libsystemd-dev

script:
- yarn run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_257dda796125_key -iv $encrypted_257dda796125_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

notifications:
  webhooks:
    urls:
      - http://orthanc.localecho.net/cgi-bin/webhook.py
    on_success: always
    on_failure: always

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/dev.fuelrats.com/
  on:
    branch: develop

- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/beta.fuelrats.com/
  on:
    branch: beta

- provider: script
  skip_cleanup: true
  script: scripts/prod-deploy.sh
  on:
    branch: master
